require: rubocop-rspec

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/ConstantName:
  Exclude:
    - 'lib/sneakers/laces/worker.rb'

Style/MutableConstant:
  Exclude:
    - 'lib/sneakers/laces/worker.rb'
